name: C++ Compile and Test

on:
  push:
    paths:
      - 'arrays/**/*.cpp'   # faqat arrays papkasidagi .cpp fayllarini push qilganda workflow ishga tushadi
  pull_request:
    paths:
      - 'arrays/**/*.cpp'   # faqat arrays papkasidagi .cpp fayllari uchun pull request yuborilganida workflow ishga tushadi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Repository'ni tekshirib olish

      - name: Set up C++ environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential  # Zarur bo'lgan C++ paketlarini o'rnatish

      - name: Find and Compile C++ code from arrays folder
        run: |
          # arrays papkasidagi barcha .cpp fayllarini topish
          cpp_files=$(find arrays -name "*.cpp")
          
          # agar cpp_files bo'sh bo'lmasa, kompilyatsiya qilish
          if [ -n "$cpp_files" ]; then
            g++ -o output $cpp_files  # Barcha topilgan .cpp fayllarni kompilyatsiya qilish
          else
            echo "No C++ files found in arrays directory"
            exit 1  # Xato qaytarish
          fi
          
      - name: Run the program (if needed)
        run: |
          ./output  # Agar dastur ishlatilsa, uni ishga tushirishingiz mumkin

      - name: Send Telegram Notification on Success
        if: success()  # Agar kompilyatsiya muvaffaqiyatli bo'lsa
        run: |
          MESSAGE="C++ build and tests passed successfully!"
          bash ./send_telegram.sh "$MESSAGE"  # Telegramga xabar yuborish

      - name: Send Telegram Notification on Failure
        if: failure()  # Agar xatolik yuzaga kelsa
        run: |
          MESSAGE="C++ build or tests failed. Please check the logs."
          bash ./send_telegram.sh "$MESSAGE"  # Telegramga xabar yuborish
