name: C++ Compile and Test for 561_array_partition.cpp

on:
  push:
    paths:
      - 'arrays/561_array_partition.cpp'   # faqat arrays papkasidagi 561_array_partition.cpp fayli push qilganda workflow ishga tushadi
  pull_request:
    paths:
      - 'arrays/561_array_partition.cpp'   # faqat arrays papkasidagi 561_array_partition.cpp fayli uchun pull request yuborilganida workflow ishga tushadi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Repository'ni tekshirib olish

      - name: Set up C++ environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential  # Zarur bo'lgan C++ paketlarini o'rnatish

      - name: Compile 561_array_partition.cpp
        run: |
          # 561_array_partition.cpp faylini kompilyatsiya qilish
          g++ arrays/561_array_partition.cpp -o output  # 561_array_partition.cpp faylini kompilyatsiya qilish
          
      - name: Run the program (if needed)
        run: |
          ./output  # Dastur muvaffaqiyatli kompilyatsiya qilinsa, uni ishga tushirish

      - name: Send Telegram Notification on Success
        if: success()  # Agar kompilyatsiya muvaffaqiyatli bo'lsa
        run: |
          MESSAGE="C++ build and tests passed successfully for 561_array_partition.cpp!"
          bash ./send_telegram.sh "$MESSAGE"  # Telegramga xabar yuborish

      - name: Send Telegram Notification on Failure
        if: failure()  # Agar xatolik yuzaga kelsa
        run: |
          MESSAGE="C++ build or tests failed for 561_array_partition.cpp. Please check the logs."
          bash ./send_telegram.sh "$MESSAGE"  # Telegramga xabar yuborish
